ant:
  hybrid:
    num_generations: 6
    sigma: 0.0125 # .0125 for TD, 0.025 for KLESPR
    sigma_decay: 0.95
    sigma_limit: 0.005
    alpha: 0.0025 # 0.0025 for TD, 0.005 for KLESPR
    checkpoint: null
    klespr_ac_point: 4800
    antithetic: true
    state_preprocessor: RunningStandardScaler
    kl_threshold: 0.1
    max_timesteps: 4800
    method: klespr